function exception_rethrow(_err){
	// Wrap exception and throw it
	throw exception_wrap(_err);
}